### ISSUE TITLE
A  couple of good things :)

### ISSUE THREAD

**Issue by aleksey-ios-dev** [klipnov/bangkok#14]
`viewModel.didUpdateSurvey = {...`
I like this approach, it results in having less spaghetti code

It's good that you write unit tests. Try to give more descriptive names to test functions. Say, 
`func testBangkokPageControl() {` could be `testThatPageControlPutsImageViewsAsSubviews`
https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530

**Comment by klipnov** [comment]
Great, Thanks
