### ISSUE TITLE
No token refresing

### ISSUE THREAD

**Issue by aleksey-ios-dev** [klipnov/bangkok#15]
As I know, a part of the task was handling of token expiration. Please, provide a mechanism to handle expired session

**Comment by klipnov** [comment]
I will try to complete it by tomorrow morning because my laptop battery finished and no charger T_T. I am implementing it using the RequestRetrier. @mmrmmlrr

**Comment by klipnov** [comment]
I have completed the handling of token expiration by using alamofire's request retrier and adapter. Saving the tokens in the keychain. @mmrmmlrr
